/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetingelserRouteImport } from './routes/betingelser'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as KasseRouteImport } from './routes/kasse'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PrivatlivRouteImport } from './routes/privatliv'
import { Route as KasseIndexRouteImport } from './routes/kasse.index'
import { Route as KasseBetalingRouteImport } from './routes/kasse.betaling'
import { Route as KasseOkRouteImport } from './routes/kasse.ok'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetingelserRoute = BetingelserRouteImport.update({
  id: '/betingelser',
  path: '/betingelser',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const KasseRoute = KasseRouteImport.update({
  id: '/kasse',
  path: '/kasse',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatlivRoute = PrivatlivRouteImport.update({
  id: '/privatliv',
  path: '/privatliv',
  getParentRoute: () => rootRouteImport,
} as any)
const KasseIndexRoute = KasseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KasseRoute,
} as any)
const KasseBetalingRoute = KasseBetalingRouteImport.update({
  id: '/betaling',
  path: '/betaling',
  getParentRoute: () => KasseRoute,
} as any)
const KasseOkRoute = KasseOkRouteImport.update({
  id: '/ok',
  path: '/ok',
  getParentRoute: () => KasseRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/betingelser': typeof BetingelserRoute
  '/cookies': typeof CookiesRoute
  '/kasse': typeof KasseRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/privatliv': typeof PrivatlivRoute
  '/kasse/betaling': typeof KasseBetalingRoute
  '/kasse/ok': typeof KasseOkRoute
  '/p/$slug': typeof PSlugRoute
  '/kasse/': typeof KasseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/betingelser': typeof BetingelserRoute
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/privatliv': typeof PrivatlivRoute
  '/kasse/betaling': typeof KasseBetalingRoute
  '/kasse/ok': typeof KasseOkRoute
  '/p/$slug': typeof PSlugRoute
  '/kasse': typeof KasseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/betingelser': typeof BetingelserRoute
  '/cookies': typeof CookiesRoute
  '/kasse': typeof KasseRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/privatliv': typeof PrivatlivRoute
  '/kasse/betaling': typeof KasseBetalingRoute
  '/kasse/ok': typeof KasseOkRoute
  '/p/$slug': typeof PSlugRoute
  '/kasse/': typeof KasseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/betingelser'
    | '/cookies'
    | '/kasse'
    | '/kontakt'
    | '/privatliv'
    | '/kasse/betaling'
    | '/kasse/ok'
    | '/p/$slug'
    | '/kasse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/betingelser'
    | '/cookies'
    | '/kontakt'
    | '/privatliv'
    | '/kasse/betaling'
    | '/kasse/ok'
    | '/p/$slug'
    | '/kasse'
  id:
    | '__root__'
    | '/'
    | '/betingelser'
    | '/cookies'
    | '/kasse'
    | '/kontakt'
    | '/privatliv'
    | '/kasse/betaling'
    | '/kasse/ok'
    | '/p/$slug'
    | '/kasse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetingelserRoute: typeof BetingelserRoute
  CookiesRoute: typeof CookiesRoute
  KasseRoute: typeof KasseRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  PrivatlivRoute: typeof PrivatlivRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betingelser': {
      id: '/betingelser'
      path: '/betingelser'
      fullPath: '/betingelser'
      preLoaderRoute: typeof BetingelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasse': {
      id: '/kasse'
      path: '/kasse'
      fullPath: '/kasse'
      preLoaderRoute: typeof KasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatliv': {
      id: '/privatliv'
      path: '/privatliv'
      fullPath: '/privatliv'
      preLoaderRoute: typeof PrivatlivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasse/': {
      id: '/kasse/'
      path: '/'
      fullPath: '/kasse/'
      preLoaderRoute: typeof KasseIndexRouteImport
      parentRoute: typeof KasseRoute
    }
    '/kasse/betaling': {
      id: '/kasse/betaling'
      path: '/betaling'
      fullPath: '/kasse/betaling'
      preLoaderRoute: typeof KasseBetalingRouteImport
      parentRoute: typeof KasseRoute
    }
    '/kasse/ok': {
      id: '/kasse/ok'
      path: '/ok'
      fullPath: '/kasse/ok'
      preLoaderRoute: typeof KasseOkRouteImport
      parentRoute: typeof KasseRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KasseRouteChildren {
  KasseBetalingRoute: typeof KasseBetalingRoute
  KasseOkRoute: typeof KasseOkRoute
  KasseIndexRoute: typeof KasseIndexRoute
}

const KasseRouteChildren: KasseRouteChildren = {
  KasseBetalingRoute: KasseBetalingRoute,
  KasseOkRoute: KasseOkRoute,
  KasseIndexRoute: KasseIndexRoute,
}

const KasseRouteWithChildren = KasseRoute._addFileChildren(KasseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetingelserRoute: BetingelserRoute,
  CookiesRoute: CookiesRoute,
  KasseRoute: KasseRouteWithChildren,
  KontaktRoute: KontaktRoute,
  PrivatlivRoute: PrivatlivRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
